server:
  port: 9000

spring:
  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET
            backoff:
              firstBackoff: 10ms
              maxBackoff: 50ms

      routes:
        - id: flights-route
          uri: ${FLIGHTS_SERVICE_URL:http://localhost:9001}
          predicates:
            - Path=/api/flights/**
          filters:
            - StripPrefix=1
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true

logging:
  level:
    reactor:
      core:
        publisher: TRACE
      netty: DEBUG
    org:
      springframework:
        cloud:
          gateway: TRACE
        security: TRACE

