server:
  port: 9000


spring:
  cloud:
    gateway:
      routes:
        - id: flights-route
          uri: http://localhost:9001
          predicates:
            - Path=/api/flights/{airport}
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-Colour, Blue-{airport}
        - id: crew-route
          uri: http://localhost:9002
          predicates:
            - Path=/api/crew/**
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-Colour, Red





logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
