server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: flights-route
          uri: ${FLIGHTS_SERVICE_URL:http://localhost:9001}
          predicates:
            - Path=/api/flights/**
          filters:
            - StripPrefix=1
  redis:
    host: localhost
    port: 6379


logging:
  level:
    reactor:
      core:
        publisher: TRACE
      netty: DEBUG
    org:
      springframework:
        cloud:
          gateway: TRACE
        security: TRACE

