server:
  port: 9000

spring:
  webflux:
    base-path: /api
  cloud:
    gateway:
      routes:
        - id: crew-and-flights-route
          uri: forward:/api/aggregate/flights/details
          predicates:
            - Path=/api/flights/details

app:
  servers:
    flights: http://localhost:9001/flights
    crew: http://localhost:9002/crew

logging:
  level:
    reactor:
      core:
        publisher: TRACE
      netty: DEBUG
    org:
      springframework:
        cloud:
          gateway: TRACE
        security: TRACE

